#!/bin/bash

# This script creates a Gitea StatefulSet from the template backed by a
# sqlite3 database stored on the persistent volume attached to the pod.
#
# The pod mounts the persistent volume with gid 0.

PROJ="$(oc project -q)"
APP="gitea"

set -e

# create a dummy route to figure out routing suffix
oc create route edge dummy --service=dummy --port=8080 -n $PROJ
SUFFIX="$(oc get route/dummy -n $PROJ -o jsonpath='{.spec.host}' | sed -e 's/^[^.]*\.//')"
oc delete route/dummy -n $PROJ

# add SCC
oc apply -f https://raw.githubusercontent.com/kwkoo/gitea-openshift/master/root-fsgroup.yaml

oc new-app \
  -n $PROJ \
  -f https://raw.githubusercontent.com/kwkoo/gitea-openshift/master/gitea-fsgroup-template.yaml \
  -p IMAGE="ghcr.io/kwkoo/gitea-openshift:1.15.2-rootless" \
  -p PROJECT="$PROJ" \
  -p DOMAIN="${APP}-${PROJ}.${SUFFIX}" \
  -p ROOT_URL="https://${APP}-${PROJ}.${SUFFIX}"

oc rollout status statefulset/${APP} -n $PROJ -w

echo "Gitea is now available at https://$(oc get route/${APP} -n $PROJ -o jsonpath='{.spec.host}')"

# To delete gitea:
# oc delete all,pvc,sa -l app=$APP -n $PROJ
# oc adm policy remove-scc-from-user root-fsgroup -z $APP -n $PROJ
# oc delete scc root-fsgroup
